# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788e6cac71c26761326d8b75742f628fe7df0d6c9240678bff839bfdc1dbf04853771167f5342d0b66d9cb90c1adaa25b08b6eb9fa1777f84b9f32d57bc28c15

test:
  secret_key_base: e18bcb790e50989a4e52f9e72f63e1211a00e1d275fd355864194989ab34947f6ee24abdc80f47346ca105a9d235075416e7d2c571d52e2645d59862643a77e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
